version: '3'
services:
  mockoon:
    image: node:14
    volumes:
      - ./mockoon:/app
    working_dir: /app
    command: [ "mockoon-cli", "start", "--data", "/app/concung.json", "--port", "3001" ]
    ports:
      - 3001:3001
  cc_swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/mnt/openapi.json
    volumes:
      - ./openapi.json:/mnt/openapi.json