version: '3'
services:

  app:
    image: fastapi-app:v1
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload" ]
    volumes:
      - .:/code
    ports:
      - 8002:8002

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /path/to/your/ssl/certificate:/etc/nginx/ssl/concung.mock_server.vn.crt
      - /path/to/your/ssl/key:/etc/nginx/ssl/concung.mock_server.vn.key
    ports:
      - "80:80"
      - "443:443"

  #  app_2:
  #    image: fastapi-app:v1
  #    restart: always
  #    container_name: app_2
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    command: [ "python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003", "--reload" ]
  #    volumes:
  #      - .:/code
  #    ports:
  #      - 8003:8003

  mock_server:
    image: mockoon/cli:latest
    container_name: mock_server
    command: [ "--data", "data", "--port", "3001" ]
    volumes:
      - ./mockoon/concung.json:/data:ro
    ports:
      - 3001:3001

  cc_swagger:
    image: swaggerapi/swagger-ui
    container_name: cc_swagger
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/mnt/openapi.json
    volumes:
      - ./openapi.json:/mnt/openapi.json

#  photoprism:
#    image: photoprism/photoprism:latest
#    restart: always
#    ports:
#      - 2342:2342 # [local port]:[container port]
#    environment:
#      PHOTOPRISM_DEBUG: "false"
#      PHOTOPRISM_PUBLIC: "true"
#    volumes:
#      - "./images/assets:/photoprism/originals" # [local path]:[container path]
#      - "./photoprism/import:/photoprism/import"
#      - "./photoprism/database:/photoprism/database"
#      - "./photoprism/sidecar:/photoprism/storage/sidecar" # [local path]:[container path]