version: '3'
services:
#  mockoon:
#    build: .
#    ports:
#      - "3000:3000"
  cc_swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/mnt/openapi.json
    volumes:
      - ./openapi.json:/mnt/openapi.json